# Using experimental CircleCI orbs
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.0.0
workflows:
  build:
    jobs:
      - cypress/run:
          record: false
          start: npm start
          filters:
            branches:
              only: "feat/e2e-testing-with-cypress"
